//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_Management.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION_T
    {
        public int ID { get; set; }
        public string APPLICATION_NAME_TX { get; set; }
        public string APPLICATIONDESC_TX { get; set; }
        public Nullable<int> WEB_APP_ID { get; set; }
        public string SCHEMA_NAME_TX { get; set; }
        public Nullable<int> MANDATORY_APP_ID { get; set; }
        public bool ACTIVE_YN { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
        public int UPDATED_BY { get; set; }
    }
}
