//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_Management.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPONSIBILITY_T
    {
        public int ID { get; set; }
        public string RESP_NAME_TX { get; set; }
        public string RESP_SYM_NAME_TX { get; set; }
        public string RESP_DESC_TX { get; set; }
        public int RESP_TYPE_NM { get; set; }
        public Nullable<int> REF_ID { get; set; }
        public bool READ_WRITE_YN { get; set; }
        public bool ACTIVE_YN { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
        public int UPDATED_BY { get; set; }
    }
}
