//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_Management.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCREEN_COMP_T
    {
        public int ID { get; set; }
        public int SCREEN_ID { get; set; }
        public Nullable<int> REF_ID { get; set; }
        public int ORDER_NM { get; set; }
        public int COMP_TYPE_NM { get; set; }
        public string COMP_CONTENT_TX { get; set; }
        public string COMP_NAME_TX { get; set; }
        public string COMP_VALUE_TX { get; set; }
        public string COMP_TEXT_TX { get; set; }
        public string COMP_STYLE_TX { get; set; }
        public string COMP_SCRIPT_TX { get; set; }
        public string SCREEN_REF_METHOD_NAME_TX { get; set; }
        public string COMP_CLASS_NAME_TX { get; set; }
        public Nullable<bool> COMP_CLASS_STATIC_YN { get; set; }
        public string COMP_METHOD_NAME_TX { get; set; }
        public Nullable<bool> COMP_METHOD_STATIC_YN { get; set; }
        public string SCHEMA_NAME_TX { get; set; }
        public string TABLE_NAME_TX { get; set; }
        public string COLUMN_NAME_TX { get; set; }
        public bool MANDATORY_YN { get; set; }
        public bool READ_WRITE_YN { get; set; }
        public string SQL_TX { get; set; }
        public string WHERE_TX { get; set; }
        public Nullable<int> REPORT_ID { get; set; }
        public bool ACTIVE_YN { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
        public int UPDATED_BY { get; set; }
    }
}
