//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_Management.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCREEN_T
    {
        public int ID { get; set; }
        public int APP_MODULE_ID { get; set; }
        public string SCREEN_NAME_TX { get; set; }
        public string SCREEN_SYM_NAME_TX { get; set; }
        public string SCREEN_TITLE_TX { get; set; }
        public string SCREEN_FILE_NAME_TX { get; set; }
        public string SCREEN_STYLE_TX { get; set; }
        public string SCREEN_SCRIPT_TX { get; set; }
        public string SCREEN_CONTENT_TX { get; set; }
        public string SCREEN_REF_CLASS_NAME_TX { get; set; }
        public string SCREEN_CLASS_NAME_TX { get; set; }
        public Nullable<bool> SCREEN_CLASS_STATIC_YN { get; set; }
        public string SCREEN_METHOD_NAME_TX { get; set; }
        public Nullable<bool> SCREEN_METHOD_STATIC_YN { get; set; }
        public Nullable<int> MANDATORY_SCR_ID { get; set; }
        public string SCHEMA_NAME_TX { get; set; }
        public string TABLE_NAME_TX { get; set; }
        public string ACTION_TX { get; set; }
        public bool ACTIVE_YN { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
        public int UPDATED_BY { get; set; }
    }
}
