//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_Management.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPER_USER_T
    {
        public long ID { get; set; }
        public string USER_ID { get; set; }
        public long USER_TYPE_ID { get; set; }
        public string USER_NAME_TX { get; set; }
        public string EMAIL_TX { get; set; }
        public string LOGIN_ID { get; set; }
        public string LOGIN_PWD_TX { get; set; }
        public bool ACTIVE_YN { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
        public int UPDATED_BY { get; set; }
    }
}
