//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_Event.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_REGISTRATION_T
    {
        public int ID { get; set; }
        public Nullable<int> EVENT_ID { get; set; }
        public string COMP_NAME_TX { get; set; }
        public string BILLING_ADDRESS_TX { get; set; }
        public string SHIPPING_ADDRESS_TX { get; set; }
        public Nullable<int> STATE_CODE_NM { get; set; }
        public string CITY_TX { get; set; }
        public string PIN_CODE_TX { get; set; }
        public string GSTIN { get; set; }
        public string EMAIL_TX { get; set; }
        public string MOB_NM_TX { get; set; }
        public string USER_ID { get; set; }
        public string PASSWORD_TX { get; set; }
        public Nullable<bool> APPROVED_YN { get; set; }
        public Nullable<bool> ACTIVE_YN { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<int> Stall_Nmber_Id { get; set; }
        public string STALLDESCRIPTION { get; set; }
        public string CONTACTPERSON { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> GSTAMOUNT { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public Nullable<decimal> CGSTAMOUNT { get; set; }
        public Nullable<decimal> SGSTAMOUNT { get; set; }
        public Nullable<decimal> IGSTAMOUNT { get; set; }
        public Nullable<decimal> UTGSTAMOUNT { get; set; }
    }
}
