//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_Event.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_USER_T
    {
        public int ID { get; set; }
        public Nullable<int> EVENT_ID { get; set; }
        public Nullable<int> REGISTER_ID { get; set; }
        public string COMP_NAME_TX { get; set; }
        public string BILLING_ADDRESS_TX { get; set; }
        public string SHIPPING_ADDRESS_TX { get; set; }
        public Nullable<int> STATE_CODE_NM { get; set; }
        public Nullable<int> CITY_NM { get; set; }
        public string PIN_CODE_TX { get; set; }
        public string GSTIN { get; set; }
        public string EMAIL_TX { get; set; }
        public string MOB_NM_TX { get; set; }
        public string USER_ID { get; set; }
        public string PASSWORD_TX { get; set; }
        public Nullable<bool> ACTIVE_YN { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<int> Stall_Number_Id { get; set; }
    }
}
