//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_Event.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_T
    {
        public int ID { get; set; }
        public int EVENT_TYPE_ID { get; set; }
        public string EVENT_NAME_TX { get; set; }
        public string EVENT_DESC_TX { get; set; }
        public System.DateTime START_DT { get; set; }
        public System.DateTime END_DT { get; set; }
        public System.DateTime REGISTRATION_START_DT { get; set; }
        public System.DateTime REGISTRATION_END_DT { get; set; }
        public string GSTIN { get; set; }
        public string SAC_CODE_TX { get; set; }
        public string GL_CODE_TX { get; set; }
        public int ACTIVE_YN { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTime UPDATED_DT { get; set; }
        public int UPDATED_BY { get; set; }
    }
}
