//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_Event.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACK_SEQ_T
    {
        public int ID { get; set; }
        public string SERIES_START_ID { get; set; }
        public string SERIES_CURRENT_ID { get; set; }
        public Nullable<bool> ACTIVE_YN { get; set; }
    }
}
