//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_Event.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentGatewayMaster
    {
        public int id { get; set; }
        public string PGCode { get; set; }
        public string PGName { get; set; }
        public string PGType { get; set; }
        public string GatewayURL { get; set; }
        public string CheckSumKey { get; set; }
        public string MerchantId { get; set; }
        public string SubMerchantID { get; set; }
        public string RefernceNo { get; set; }
        public string ReturnURL { get; set; }
        public Nullable<bool> ISActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
