//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_eCSIN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ICSI_eCSIN_DBModelEntities : DbContext
    {
        public ICSI_eCSIN_DBModelEntities()
            : base("name=ICSI_eCSIN_DBModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbleCSINGeneration> tbleCSINGenerations { get; set; }
        public virtual DbSet<tbleCSINGenerationHistory> tbleCSINGenerationHistories { get; set; }
        public virtual DbSet<tblGenerateeCSIN> tblGenerateeCSINs { get; set; }
        public virtual DbSet<tblSubsidiaryUser> tblSubsidiaryUsers { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    
        public virtual ObjectResult<GetTotalUsereCSIN_Result> GetTotalUsereCSIN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTotalUsereCSIN_Result>("GetTotalUsereCSIN");
        }
    }
}
