//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSI_UDIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDINVerificationDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public string UDINNumber { get; set; }
    
        public virtual UDINVerificationDetail UDINVerificationDetail1 { get; set; }
        public virtual UDINVerificationDetail UDINVerificationDetail2 { get; set; }
    }
}
